from enum import Enum


class EventType(Enum):
    """
    Enum for all event types.
    """

    COMPLETE_GOOGLE_API_PHONEME_TRANSFORMATION = 1,
    TRANSCRIBE_USING_GOOGLE_API = 2,
    TRANSLATE_USING_GOOGLE_API = 3,
    SEND_PHONEMES_TO_MICROCONTROLLER = 4,
    SEND_SENTENCES_TO_MICROCONTROLLER = 5,
    TRANSCRIBE_AND_TRANSLATE_USING_GOOGLE_API = 6.
